"""Canonical exhaustive enumeration of ordered full tree shapes."""

from __future__ import annotations

from functools import lru_cache
from itertools import product
from typing import Iterable, Iterator, Sequence, TypeAlias

import numpy as np

from .typed_tree import Leaf, Node, Tree, shape_signature


Shape: TypeAlias = None | tuple["Shape", ...]


def _weak_compositions(total: int, parts: int) -> Iterator[tuple[int, ...]]:
    if parts == 1:
        yield (total,)
        return
    for first in range(total + 1):
        for remainder in _weak_compositions(total - first, parts - 1):
            yield (first, *remainder)


@lru_cache(maxsize=None)
def full_ordered_shapes(internal_nodes: int, arity: int) -> tuple[Shape, ...]:
    """Enumerate all ordered full ``arity``-ary shapes with exactly ``k`` nodes."""

    if internal_nodes < 0:
        raise ValueError("internal_nodes must be nonnegative")
    if arity < 2:
        raise ValueError("arity must be at least two")
    if internal_nodes == 0:
        return (None,)
    result: list[Shape] = []
    for allocation in _weak_compositions(internal_nodes - 1, arity):
        child_families = [full_ordered_shapes(count, arity) for count in allocation]
        result.extend(tuple(children) for children in product(*child_families))
    return tuple(result)


@lru_cache(maxsize=None)
def mixed_ordered_shapes(
    internal_nodes: int, arities: tuple[int, ...] = (2, 3, 4)
) -> tuple[Shape, ...]:
    """Enumerate all ordered full shapes generated by a mixed-arity grammar."""

    if internal_nodes < 0:
        raise ValueError("internal_nodes must be nonnegative")
    if not arities or any(arity < 2 for arity in arities):
        raise ValueError("the grammar must contain arities of at least two")
    if internal_nodes == 0:
        return (None,)
    result: list[Shape] = []
    for arity in sorted(set(arities)):
        for allocation in _weak_compositions(internal_nodes - 1, arity):
            child_families = [mixed_ordered_shapes(count, arities) for count in allocation]
            result.extend(tuple(children) for children in product(*child_families))
    return tuple(result)


def count_fixed_arity(internal_nodes: int, arity: int) -> int:
    return len(full_ordered_shapes(internal_nodes, arity))


def count_mixed(internal_nodes: int, arities: Sequence[int] = (2, 3, 4)) -> int:
    return len(mixed_ordered_shapes(internal_nodes, tuple(arities)))


def label_shape(
    shape: Shape,
    *,
    law_prefix: str = "mu",
    type_name: str = "tau",
    leaf_start: int = 0,
    repeated_law: bool = False,
) -> Tree:
    """Turn an untyped shape into a canonically labeled homogeneous tree."""

    next_leaf = leaf_start
    next_node = 0

    def visit(current: Shape) -> Tree:
        nonlocal next_leaf, next_node
        if current is None:
            result = Leaf(next_leaf, type_name)
            next_leaf += 1
            return result
        children = tuple(visit(child) for child in current)
        law_id = law_prefix if repeated_law else f"{law_prefix}_{next_node}"
        next_node += 1
        return Node(law_id, type_name, children)

    return visit(shape)


def topology_family_shape(
    internal_nodes: int,
    arity: int,
    family: str,
    *,
    seed: int = 0,
) -> Shape:
    """Construct a deterministic representative of a declared topology family."""

    if internal_nodes < 0 or arity < 2:
        raise ValueError("invalid tree parameters")
    if internal_nodes == 0:
        return None

    def build(k: int, mode: str, rng: np.random.Generator) -> Shape:
        if k == 0:
            return None
        remaining = k - 1
        if mode in {"left_comb", "low_strahler"}:
            allocation = [remaining, *(0 for _ in range(arity - 1))]
        elif mode == "right_comb":
            allocation = [*(0 for _ in range(arity - 1)), remaining]
        elif mode == "minimally_balanced":
            slot = (k + arity // 2) % arity
            allocation = [0] * arity
            allocation[slot] = remaining
        elif mode in {"maximally_balanced", "balanced", "high_strahler", "repeated_subtree"}:
            quotient, remainder = divmod(remaining, arity)
            allocation = [quotient + (1 if index < remainder else 0) for index in range(arity)]
            if mode == "repeated_subtree" and remainder:
                allocation = allocation[-remainder:] + allocation[:-remainder]
        elif mode in {"random_ordered", "random"}:
            cuts = sorted(rng.integers(0, remaining + 1, size=arity - 1).tolist())
            boundaries = [0, *cuts, remaining]
            allocation = [boundaries[index + 1] - boundaries[index] for index in range(arity)]
            rng.shuffle(allocation)
        else:
            raise ValueError(f"unknown topology family {mode!r}")
        return tuple(build(count, mode, rng) for count in allocation)

    return build(internal_nodes, family, np.random.default_rng(seed))


def shape_code(shape: Shape, *, ordered: bool = True) -> str:
    """Return a stable shape identifier without constructing typed nodes."""

    tree = label_shape(shape)
    return shape_signature(tree, ordered=ordered)


def enumerate_targets() -> dict[str, list[Shape]]:
    """Materialize exactly the four exhaustive v3 target families."""

    return {
        "binary": [shape for k in range(1, 9) for shape in full_ordered_shapes(k, 2)],
        "ternary": [shape for k in range(1, 6) for shape in full_ordered_shapes(k, 3)],
        "quaternary": [shape for k in range(1, 5) for shape in full_ordered_shapes(k, 4)],
        "mixed": [shape for k in range(1, 6) for shape in mixed_ordered_shapes(k)],
    }


def filter_typed_trees(candidates: Iterable[Tree], validator) -> list[Tree]:
    """Filter a grammar with a caller-supplied type validator."""

    accepted: list[Tree] = []
    for candidate in candidates:
        try:
            validator(candidate)
        except ValueError:
            continue
        accepted.append(candidate)
    return accepted
