"""Re-derive the optimality classification and its dependent tables and macros.

The status of a certified enclosure is a pure function of the certified lower and upper
bounds, which are already recorded in the committed artifacts. Correcting the classifier
therefore does not require re-running the (expensive) constants pipeline: the corrected
classifier is re-applied to the bounds that are already on disk.

Historical computational outputs under ``artifacts/`` are never modified. The corrected
tables, macros and reclassified copies of the registries are written into the delivery
package instead, so that the original and the corrected derivation can be compared.

Usage::

    python scripts/regenerate_optimality_classification.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

import sys  # noqa: E402

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from seion_core.research_v3.interval_certification import (  # noqa: E402
    EXACTLY_DETERMINED_POSITIVE,
    EXACTLY_ZERO_BY_THEOREM,
    NO_POSITIVE_LOWER_BOUND_OBTAINED,
    POSITIVE_LOWER_BOUND_WITH_NONZERO_GAP,
    classify_optimality,
)

INDEX = ROOT / "artifacts" / "index"
RESEARCH = ROOT / "artifacts" / "research_v3"
PACKAGE = ROOT / "academic_submission_package"
PAPER = PACKAGE / "sources" / "recursive_projection_of_multilinear_trees"
DATA_OUT = PAPER / "data"
TABLE_OUT = PAPER / "tables"

CLASSES = (
    EXACTLY_DETERMINED_POSITIVE,
    EXACTLY_ZERO_BY_THEOREM,
    POSITIVE_LOWER_BOUND_WITH_NONZERO_GAP,
    NO_POSITIVE_LOWER_BOUND_OBTAINED,
)

#: Prose used in the manuscripts. The identifiers above never appear there.
PROSE = {
    EXACTLY_DETERMINED_POSITIVE: "constant determined exactly (positive value)",
    EXACTLY_ZERO_BY_THEOREM: "null case, an immediate consequence of the theorem",
    POSITIVE_LOWER_BOUND_WITH_NONZERO_GAP: (
        "positive lower and upper bounds that do not yet coincide"
    ),
    NO_POSITIVE_LOWER_BOUND_OBTAINED: "no positive lower bound obtained",
}


def reclassify(frame: pd.DataFrame) -> pd.DataFrame:
    """Return ``frame`` with a recomputed ``optimality_class`` column."""
    classes = [
        classify_optimality(low, up)
        for low, up in zip(
            frame["certified_lower_bound"], frame["certified_upper_bound"], strict=True
        )
    ]
    return frame.assign(optimality_class=classes)


def counts(frame: pd.DataFrame) -> dict[str, int]:
    return {name: int((frame["optimality_class"] == name).sum()) for name in CLASSES}


def fmt_int(value: int) -> str:
    return f"{int(value):,}".replace(",", "{,}")


def num(value: float) -> str:
    if pd.isna(value):
        return r"{--}"
    return f"{float(value):.4g}"


def write_gap_table(gaps: pd.DataFrame) -> Path:
    lines = [
        "% Generated by scripts/regenerate_optimality_classification.py.",
        "% One row per error type. The four class columns are mutually exclusive and",
        "% sum to the configuration count.",
        r"\begin{tabular}{@{}lrrrrrS@{}}",
        r"\toprule",
        r"& & \multicolumn{4}{c}{outcome} & \\",
        r"\cmidrule(lr){3-6}",
        r"error type & \# & determined & zero & partial & none "
        r"& \multicolumn{1}{c}{median gap} \\",
        r"\midrule",
    ]
    for error, group in gaps.groupby("error_type", sort=True):
        c = counts(group)
        lines.append(
            f"{error} & {len(group)} & {c[EXACTLY_DETERMINED_POSITIVE]} & "
            f"{c[EXACTLY_ZERO_BY_THEOREM]} & {c[POSITIVE_LOWER_BOUND_WITH_NONZERO_GAP]} & "
            f"{c[NO_POSITIVE_LOWER_BOUND_OBTAINED]} & "
            f"{num(group['absolute_gap'].median())} \\\\"
        )
    total = counts(gaps)
    lines += [
        r"\midrule",
        f"all & {len(gaps)} & {total[EXACTLY_DETERMINED_POSITIVE]} & "
        f"{total[EXACTLY_ZERO_BY_THEOREM]} & {total[POSITIVE_LOWER_BOUND_WITH_NONZERO_GAP]} & "
        f"{total[NO_POSITIVE_LOWER_BOUND_OBTAINED]} & {num(gaps['absolute_gap'].median())} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    path = TABLE_OUT / "optimality_gaps.tex"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_macros(gaps: pd.DataFrame, atlas: pd.DataFrame, existing: Path) -> Path:
    """Rewrite generated_results.tex, replacing the classification macros."""
    g = counts(gaps)
    a = counts(atlas)
    n = len(gaps)
    replacements = {
        r"\VThreeDeterminedPositive": fmt_int(g[EXACTLY_DETERMINED_POSITIVE]),
        r"\VThreeZeroByTheorem": fmt_int(g[EXACTLY_ZERO_BY_THEOREM]),
        r"\VThreePartialLowerBound": fmt_int(g[POSITIVE_LOWER_BOUND_WITH_NONZERO_GAP]),
        r"\VThreeNoPositiveLowerBound": fmt_int(g[NO_POSITIVE_LOWER_BOUND_OBTAINED]),
        r"\VThreeGapRegistryRows": fmt_int(n),
        r"\VThreeNoPositiveLowerPercent": (
            rf"\num{{{100.0 * g[NO_POSITIVE_LOWER_BOUND_OBTAINED] / n:.1f}}}"
        ),
        r"\VThreeAtlasDeterminedPositive": fmt_int(a[EXACTLY_DETERMINED_POSITIVE]),
        r"\VThreeAtlasZeroByTheorem": fmt_int(a[EXACTLY_ZERO_BY_THEOREM]),
    }
    # Always rebuild from the pristine pipeline output so that repeated runs are
    # idempotent rather than appending a second block of macros.
    dropped = (
        r"\VThreeExactCells",  # counted the vacuous and the determined cases together
        r"\VThreeMaxRelativeGap",  # a value of 1 means "no positive lower bound"
        r"\VThreeReleaseStatus",  # an internal status code, not scholarly prose
    )
    kept = []
    for line in existing.read_text(encoding="utf-8").splitlines():
        if any(name in line for name in dropped):
            continue
        kept.append(line)
    kept.append("% Optimality classification, re-derived by")
    kept.append("% scripts/regenerate_optimality_classification.py from the certified")
    kept.append("% bounds in artifacts/index/optimality_gaps_v3.csv and")
    kept.append("% artifacts/research_v3/block_A_exact_atlas.csv.")
    for name, value in replacements.items():
        kept.append(rf"\newcommand{{{name}}}{{{value}}}")
    path = PAPER / "generated_results.tex"
    path.write_text("\n".join(kept) + "\n", encoding="utf-8")
    return path


def main() -> None:
    DATA_OUT.mkdir(parents=True, exist_ok=True)
    TABLE_OUT.mkdir(parents=True, exist_ok=True)

    gaps = reclassify(pd.read_csv(INDEX / "optimality_gaps_v3.csv"))
    atlas = reclassify(pd.read_csv(RESEARCH / "block_A_exact_atlas.csv"))

    gaps.to_csv(DATA_OUT / "optimality_gaps_reclassified.csv", index=False)
    atlas[
        [
            "error_type",
            "certified_lower_bound",
            "certified_upper_bound",
            "absolute_gap",
            "relative_gap",
            "optimality_class",
        ]
    ].to_csv(DATA_OUT / "exact_atlas_reclassified.csv", index=False)

    summary = {
        "source_gap_registry": "artifacts/index/optimality_gaps_v3.csv",
        "source_exact_atlas": "artifacts/research_v3/block_A_exact_atlas.csv",
        "method": (
            "The optimality class is a pure function of the certified lower and upper "
            "bounds. The corrected classifier was re-applied to the bounds already "
            "recorded in the committed artifacts. No experiment was re-run and no "
            "historical artifact was modified."
        ),
        "gap_registry_rows": len(gaps),
        "gap_registry_counts": counts(gaps),
        "gap_registry_counts_by_error_type": {
            str(k): counts(v) for k, v in gaps.groupby("error_type", sort=True)
        },
        "exact_atlas_rows": len(atlas),
        "exact_atlas_counts": counts(atlas),
        "exact_atlas_counts_by_error_type": {
            str(k): counts(v) for k, v in atlas.groupby("error_type", sort=True)
        },
        "prose_labels": PROSE,
        "maximum_absolute_gap": float(gaps["absolute_gap"].max()),
        "relative_gap_definition": "(upper - lower) / upper; a value of 1 means lower == 0",
    }
    (DATA_OUT / "optimality_classification_summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )

    write_gap_table(gaps)
    write_macros(gaps, atlas, ROOT / "papers" / "tree_stability_v4" / "generated_results.tex")

    print(json.dumps({k: summary[k] for k in ("gap_registry_rows", "gap_registry_counts",
                                              "exact_atlas_rows", "exact_atlas_counts")}, indent=2))


if __name__ == "__main__":
    main()
